IMPORT_FUNS <- list(
  read.csv = baseImportFun("read.csv", con_arg_name = "file", arg_pos = 1)
  ,read.csv2 = baseImportFun("read.csv2", con_arg_name = "file", arg_pos = 1)
  ,read.delim = baseImportFun("read.delim", con_arg_name = "file", arg_pos = 1)
  ,read.delim2 = baseImportFun("read.delim", con_arg_name = "file", arg_pos = 1)
  ,read.table = baseImportFun("read.table", con_arg_name = "file", arg_pos = 1)
  ,read.fwf = baseImportFun("read.fwf", con_arg_name = "file", arg_pos = 1)
  ,read_csv = baseImportFun("read_csv", con_arg_name = "file", arg_pos = 1)
  ,read_csv2 = baseImportFun("read_csv2", con_arg_name = "file", arg_pos = 1)
  ,read_tsv = baseImportFun("read_tsv", con_arg_name = "file", arg_pos = 1)
  ,read_table = baseImportFun("read_table", con_arg_name = "file", arg_pos = 1)
  ,read_file = baseImportFun("read_file", con_arg_name = "file", arg_pos = 1)
  ,read_fwf = baseImportFun("read_fwf", con_arg_name = "file", arg_pos = 1)
  ,read_xls = baseImportFun("read_xls", con_arg_name = "path", arg_pos = 1)
  ,read_excel = baseImportFun("read_excel", con_arg_name = "path", arg_pos = 1)
  ,read_xlsx = baseImportFun("read_xlsx", con_arg_name = "path", arg_pos = 1)
  ,fread = baseImportFun("fread", con_arg_name = "input", arg_pos = 1)
  ,getTable = getTableImportFun("getTable", dataset = "local", source ="local_env")
)

